"""
Google Calendar integration via Service Account (no Workspace required).

Flow:
- Service account is shared as a writer on the OWNER_CALENDAR_ID calendar
  (the owner does this manually in Google Calendar UI: Settings > Share with
  specific people > paste the service account email > "Make changes to events").
- Service account creates events directly on that calendar.
- Both doctor and patient are added as attendees and receive invite emails
  (sendUpdates='all').
- Google Meet links cannot be auto-generated by service accounts on personal
  (non-Workspace) calendars. We use STATIC_MEET_LINK (a permanent Meet link
  the owner created once via meet.new) injected into the event description.

Future migration to Workspace:
- Enable domain-wide delegation, set OWNER_CALENDAR_ID to a Workspace user,
  re-introduce conferenceData in the event body, drop STATIC_MEET_LINK.
"""

import os
import json
import logging
from datetime import datetime

try:
    from google.oauth2 import service_account
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
    GOOGLE_LIBS_AVAILABLE = True
except ImportError:
    GOOGLE_LIBS_AVAILABLE = False
    logging.warning("Google API libraries not installed")


SCOPES = [
    'https://www.googleapis.com/auth/calendar',
    'https://www.googleapis.com/auth/calendar.events',
]
TIMEZONE = 'Asia/Karachi'


class GoogleCalendarServiceAccount:
    def __init__(self):
        self.credentials = None
        self.has_credentials = False
        self.service_account_email = None
        self._initialize_credentials()

    def _initialize_credentials(self):
        if not GOOGLE_LIBS_AVAILABLE:
            logging.error("Google API libraries not available")
            return

        key_data = self._load_key_data()
        if not key_data:
            return

        required = ['type', 'project_id', 'private_key_id', 'private_key', 'client_email']
        missing = [f for f in required if f not in key_data]
        if missing:
            logging.error(f"Service account key missing fields: {missing}")
            return

        try:
            self.credentials = service_account.Credentials.from_service_account_info(
                key_data, scopes=SCOPES
            )
            self.service_account_email = key_data.get('client_email')
            self.has_credentials = True
            logging.info(f"✅ Calendar service account initialized: {self.service_account_email}")
        except Exception as e:
            logging.error(f"Failed to build credentials: {e}")

    def _load_key_data(self):
        # Production: env var (injected from Secret Manager).
        env_key = os.environ.get('GOOGLE_SERVICE_ACCOUNT_KEY')
        if env_key:
            try:
                return json.loads(env_key)
            except json.JSONDecodeError as e:
                logging.error(f"GOOGLE_SERVICE_ACCOUNT_KEY is not valid JSON: {e}")
                return None

        # Fallback: file baked into image at /app/service_account_key.json.
        key_file = os.path.join(
            os.path.dirname(os.path.dirname(__file__)),
            'service_account_key.json',
        )
        if os.path.exists(key_file):
            try:
                with open(key_file, 'r') as f:
                    return json.load(f)
            except Exception as e:
                logging.error(f"Failed to read {key_file}: {e}")
                return None

        logging.warning("No GOOGLE_SERVICE_ACCOUNT_KEY env var and no service_account_key.json file")
        return None

    def _get_service(self):
        """Build a Calendar API client. No impersonation (no domain-wide delegation)."""
        if not self.has_credentials:
            return None
        try:
            return build('calendar', 'v3', credentials=self.credentials, cache_discovery=False)
        except Exception as e:
            logging.error(f"Failed to build Calendar service: {e}")
            return None

    def create_appointment_event(self, appointment_data):
        """
        Create a single event on the owner's calendar with both attendees.

        appointment_data:
            doctor_email, patient_email, doctor_name, patient_name,
            start_time, end_time, symptoms, appointment_id

        Returns dict:
            { success, event_id, html_link, meet_link, error? }
        """
        if not self.has_credentials:
            return {'success': False, 'error': 'Service account not configured'}

        service = self._get_service()
        if not service:
            return {'success': False, 'error': 'Could not build Calendar service'}

        owner_calendar_id = os.environ.get('OWNER_CALENDAR_ID')
        if not owner_calendar_id:
            logging.error("OWNER_CALENDAR_ID env var not set")
            return {'success': False, 'error': 'OWNER_CALENDAR_ID not configured'}

        static_meet_link = os.environ.get('STATIC_MEET_LINK', '').strip()

        start_time = appointment_data['start_time']
        end_time = appointment_data['end_time']
        if isinstance(start_time, str):
            start_time = datetime.fromisoformat(start_time.replace('Z', '+00:00'))
        if isinstance(end_time, str):
            end_time = datetime.fromisoformat(end_time.replace('Z', '+00:00'))

        doctor_email = appointment_data.get('doctor_email', '')
        patient_email = appointment_data.get('patient_email', '')
        doctor_name = appointment_data.get('doctor_name', 'Doctor')
        patient_name = appointment_data.get('patient_name', 'Patient')
        symptoms = appointment_data.get('symptoms', 'Not specified')
        appointment_id = appointment_data.get('appointment_id', 'N/A')

        description_lines = [
            "Auto-scheduled consultation — Red Dot Pharmacy.",
            "",
            f"Doctor:  {doctor_name}",
            f"Patient: {patient_name}",
            f"Symptoms: {symptoms}",
            f"Appointment ID: {appointment_id}",
        ]
        if static_meet_link:
            description_lines += [
                "",
                "Join the consultation via Google Meet:",
                static_meet_link,
            ]

        attendees = [e for e in [doctor_email, patient_email] if e]

        event_body = {
            'summary': 'Online Consultation — Red Dot Pharmacy',
            'description': "\n".join(description_lines),
            'start': {'dateTime': start_time.isoformat(), 'timeZone': TIMEZONE},
            'end':   {'dateTime': end_time.isoformat(),   'timeZone': TIMEZONE},
            'attendees': [{'email': e} for e in attendees],
            'reminders': {
                'useDefault': False,
                'overrides': [
                    {'method': 'email', 'minutes': 60},
                    {'method': 'popup', 'minutes': 15},
                ],
            },
            'guestsCanModify': False,
            'guestsCanInviteOthers': False,
        }

        try:
            created = service.events().insert(
                calendarId=owner_calendar_id,
                body=event_body,
                sendUpdates='all',
            ).execute()
            event_id = created.get('id')
            html_link = created.get('htmlLink')
            logging.info(f"✅ Calendar event created: {event_id}")
            return {
                'success': True,
                'event_id': event_id,
                'html_link': html_link,
                'meet_link': static_meet_link or None,
            }
        except HttpError as e:
            status = getattr(e.resp, 'status', None)
            body = e.content.decode('utf-8', errors='replace') if hasattr(e, 'content') else str(e)
            logging.error(f"Calendar API error (status={status}): {body}")
            return {
                'success': False,
                'error': f"Calendar API error: status={status}",
                'meet_link': static_meet_link or None,
            }
        except Exception as e:
            logging.error(f"Unexpected error creating event: {e}")
            return {
                'success': False,
                'error': str(e),
                'meet_link': static_meet_link or None,
            }

    # ── Backwards-compatible wrapper ───────────────────────────────────────
    # Existing callers in routes/appointment_routes.py use this method name.
    # We keep the signature/return shape to avoid touching them more than
    # necessary, but internally the logic is now single-event creation on the
    # owner's calendar.
    def create_event_for_both_calendars(self, appointment_data):
        result = self.create_appointment_event(appointment_data)
        return {
            'success': bool(result.get('success')),
            'meet_link': result.get('meet_link'),
            'doctor_event': {
                'event_id': result.get('event_id'),
                'html_link': result.get('html_link'),
                'meet_link': result.get('meet_link'),
                'success': bool(result.get('success')),
            } if result.get('event_id') else None,
            'patient_event': None,  # single-event flow, patient is just an attendee
            'error': result.get('error'),
        }

    def update_event(self, event_id, updates):
        if not self.has_credentials or not event_id:
            return None
        service = self._get_service()
        if not service:
            return None
        owner_calendar_id = os.environ.get('OWNER_CALENDAR_ID')
        if not owner_calendar_id:
            return None
        try:
            event = service.events().get(calendarId=owner_calendar_id, eventId=event_id).execute()
            for key in ('summary', 'description'):
                if key in updates:
                    event[key] = updates[key]
            if updates.get('status') == 'cancelled':
                event['status'] = 'cancelled'
            return service.events().update(
                calendarId=owner_calendar_id,
                eventId=event_id,
                body=event,
                sendUpdates='all',
            ).execute()
        except HttpError as e:
            status = getattr(e.resp, 'status', None)
            if status in (404, 410):
                logging.warning(f"Calendar event {event_id} not found or gone (status={status})")
                return None
            logging.error(f"Update event {event_id} failed: status={status}")
            return None
        except Exception as e:
            logging.error(f"Update event {event_id} failed: {e}")
            return None

    def delete_event(self, event_id):
        if not self.has_credentials or not event_id:
            return False
        service = self._get_service()
        if not service:
            return False
        owner_calendar_id = os.environ.get('OWNER_CALENDAR_ID')
        if not owner_calendar_id:
            return False
        try:
            service.events().delete(
                calendarId=owner_calendar_id,
                eventId=event_id,
                sendUpdates='all',
            ).execute()
            return True
        except HttpError as e:
            status = getattr(e.resp, 'status', None)
            if status in (404, 410):
                # Event already gone — treat as success.
                return True
            logging.error(f"Delete event {event_id} failed: status={status}")
            return False
        except Exception as e:
            logging.error(f"Delete event {event_id} failed: {e}")
            return False

    def reinitialize(self):
        self.credentials = None
        self.has_credentials = False
        self.service_account_email = None
        self._initialize_credentials()
        return self.has_credentials

    def check_service_account_setup(self):
        if not self.has_credentials:
            self.reinitialize()

        owner_calendar_id = os.environ.get('OWNER_CALENDAR_ID')
        static_meet_link = os.environ.get('STATIC_MEET_LINK')

        issues = []
        if not GOOGLE_LIBS_AVAILABLE:
            issues.append("Google API libraries not installed")
        if not self.has_credentials:
            issues.append("Service account credentials not loaded (set GOOGLE_SERVICE_ACCOUNT_KEY)")
        if not owner_calendar_id:
            issues.append("OWNER_CALENDAR_ID env var not set")
        if not static_meet_link:
            issues.append("STATIC_MEET_LINK env var not set (events will be created without a Meet link)")

        return {
            'has_credentials': self.has_credentials,
            'service_account_email': self.service_account_email,
            'owner_calendar_id': owner_calendar_id,
            'static_meet_link_configured': bool(static_meet_link),
            'libraries_available': GOOGLE_LIBS_AVAILABLE,
            'issues': issues,
        }


calendar_service_account = GoogleCalendarServiceAccount()
